In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(4)

array([0.03488113, 0.47186748, 0.03426653, 0.68992447])

In [29]:
np.random.rand(4,4)

array([[0.50451965, 0.15835366, 0.85504463, 0.17578088],
       [0.64680453, 0.29644008, 0.92551954, 0.99052385],
       [0.50141264, 0.33280441, 0.66753718, 0.19270554],
       [0.00102323, 0.00837606, 0.15566802, 0.34399995]])

In [32]:
np.random.randn(4,4)

array([[ 1.45806291,  0.51203615,  0.80781327,  0.16229052],
       [ 1.2124893 ,  0.4169337 , -0.64166188,  1.34834498],
       [-0.37909452, -0.82381125, -1.35500256,  1.41954844],
       [ 0.65294215,  0.06424153,  1.05600705, -2.76288786]])

In [35]:
np.random.randint(1,1000)

787

In [36]:
np.random.randint(1,1000,10)

array([239, 902, 668, 318, 180, 957, 667, 950, 774, 589])

In [38]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
randarr = np.random.randint(0,50,10)
randarr

array([45, 29, 27, 47, 25, 45, 41, 10,  2, 14])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
randarr.max()

47

In [52]:
randarr.min()

2

In [53]:
randarr.argmin()

8

In [54]:
randarr.argmax()

3

In [56]:
arr.shape

(25,)

In [57]:
arr = arr.reshape(5,5)

In [58]:
arr.shape

(5, 5)

In [59]:
arr.dtype

dtype('int32')

In [68]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [65]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [70]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[1:5] = 100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
slice_of_arr = arr[1:6]
slice_of_arr

array([1, 2, 3, 4, 5])

In [77]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [78]:
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy = arr.copy()
arr_copy

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_copy[:]= 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [82]:
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [83]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
arr_2d[0][2]

15

In [89]:
arr_2d[1,1]

25

In [90]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [95]:
arr_2d[1:,1:]

array([[25],
       [40]])

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [100]:
bool_arr = arr > 5

In [101]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [102]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [105]:
arr[arr<4]

array([1, 2, 3])

In [106]:
arr = np.arange(0,50).reshape(5,10)

In [107]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [108]:
arr[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [109]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [110]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [112]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [122]:
arr = arr + 100

In [123]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [126]:
1/0

ZeroDivisionError: division by zero

In [127]:
arr / arr

C:\Users\swapn\AppData\Local\Temp\ipykernel_15396\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [128]:
1 / arr

C:\Users\swapn\AppData\Local\Temp\ipykernel_15396\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [129]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [132]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [133]:
np.max(arr)

10

In [134]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [136]:
np.log(arr)

C:\Users\swapn\AppData\Local\Temp\ipykernel_15396\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])